name: CI

on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: 'Install node'
      uses: actions/setup-node@v1
    - name: 'Install NPM dependencies'
      run: npm install
    - name: 'Run code'
      run: node index.js
      env:
        NEXMO_KEY: ${{ secrets.NEXMO_KEY }}
        NEXMO_SECRET: ${{ secrets.NEXMO_SECRET }}
        NEXMO_FROM: ${{ secrets.NEXMO_FROM }}
        NEXMO_TO: ${{ secrets.NEXMO_TO }}
